# Generated by Django 3.2 on 2023-10-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_maker_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
